alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
features:
- buildpack-stack=ubuntu-22
ingress:
  rules:
  - component:
      name: vontor-cz
    match:
      path:
        prefix: /
name: shark-app
region: fra
services:
- dockerfile_path: dockerfile
  registry: registry.digitalocean.com/vontor-cz #REGISTRY!!!!
  envs:
  - key: DATABASE_HOST
    scope: RUN_AND_BUILD_TIME
    value: 100.87.184.113
  - key: DATABASE_PORT
    scope: RUN_AND_BUILD_TIME
    value: "5432"
  - key: DATABASE_ENGINE
    scope: RUN_AND_BUILD_TIME
    value: django.db.backends.postgresql
  - key: DATABASE_NAME
    scope: RUN_AND_BUILD_TIME
    value: bruno_rasp_db
  - key: DATABASE_USER
    scope: RUN_AND_BUILD_TIME
    value: vontor_cz_pi
  - key: DATABASE_PASSWORD
    scope: RUN_AND_BUILD_TIME
    value: awsmivylizePrdel1989
  - key: TAILSCALE_API_KEY
    scope: RUN_AND_BUILD_TIME
    value: tskey-auth-kjdaZQyck311CNTRL-tJZHFqGiF2KmPt5bMCcD2KPP9C7kkojF
  - key: AWS_ACCESS_KEY_ID
    scope: RUN_AND_BUILD_TIME
    value: AKIA6GBMCJ7F545FLBHC
  - key: AWS_SECRET_ACCESS_KEY
    scope: RUN_AND_BUILD_TIME
    value: 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
  - key: AWS_STORAGE_BUCKET_NAME
    scope: RUN_AND_BUILD_TIME
    value: vontor-cz
  - key: AWS_S3_REGION_NAME
    scope: RUN_AND_BUILD_TIME
    value: eu-central-1
  - key: DEBUG
    scope: RUN_AND_BUILD_TIME
    value: "True"
  github:
    branch: main
    deploy_on_push: true
    repo: Brunobrno/vontor-cz
  http_port: 8000
  instance_count: 1
  instance_size_slug: apps-s-1vcpu-0.5gb
  name: vontor-cz
  source_dir: /
