# Generated by Django 5.1.3 on 2024-11-25 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anonmessage',
            old_name='message',
            new_name='text',
        ),
    ]
